version: '3'
services:
  midjourney-web:
    container_name: midjourney-web
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      VITE_MIDJOURNEY_PROXY_URL: ${VITE_MIDJOURNEY_PROXY_URL}
      VITE_MIDJOURNEY_PROXY_API_SECRET: ${VITE_MIDJOURNEY_PROXY_API_SECRET}
    ports:
      - 8090:8090
    restart: unless-stopped
    depends_on:
      - midjourney-proxy
